### ISSUE TITLE
Code lacks LICENSE file

### ISSUE THREAD

**Issue by cdalitz** [QianZheng/BSplineFitting#1]
Many thanks for uploading an implementation of  "Fitting B-spline Curves to Point Clouds
by Curvature-Based Squared Distance Minimization" on github.

Unfortunately, the code does not contain information about the licensing terms for reuse.
Can you please add a file LICENSE (e.g. a two clause BSD license, or what you prefer) to clarify whether modification and use of the code in a BSD or GPL licensed project is permitted?

**Comment by h00shi** [comment]
No license often means public domain code.

**Comment by QianZheng** [comment]
Thanks, I add MIT license.
