### ISSUE TITLE
Fitting open bspline

### ISSUE THREAD

**Issue by rdecharette** [QianZheng/BSplineFitting#2]
Hello,

thanks for very useful implementation. I used it in a context of a research on 3D object extraction. Your code is very useful to fit object profile points to spline.

Is it possible to also fit **open** bsplines with your code ? or do you know other implementation doing so ?
Of course I will mention your code upon publication of my work.

**Comment by patripfr** [comment]
@rdecharette I was searching for exactly the same thing, and I found it in the following fork of this repo. It seems like @QianZheng implemented it in an earlier version but it can not be found in the current one. I used the version below and it worked fine for my purposes.
https://github.com/Joey4s6l/BSplineFitting

**Comment by rdecharette** [comment]
Thanks a lot, that was really useful. Indeed they have implemented Open BSpline fitting there.

Thanks.
